name: Node.js CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Instalar Jest
              run: npm install jest --save-dev
            - name: Verificar Jest
              run: ls -l node_modules/.bin/jest
            - name: Asignar permisos a Jest
              run: chmod +x node_modules/.bin/jest
            - name: Ejecutar tests
              run: npm test
