name: Publicar imagen en Docker Hub
on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del código
              uses: actions/checkout@v4

            - name: Configurar Docker
              uses: docker/setup-buildx-action@v3

            - name: Login en Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Construir y etiquetar la imagen
              run: |
                  docker build -t dakardu/app-node:latest .
                  docker tag dakardu/app-node:latest dakardu/app-node:latest

            - name: Subir imagen a Docker Hub
              run: docker push dakardu/app-node:latest
